kafka:
  applicationId: end-to-end
  bootstrappingTimeout: 60
  brokers: ${KAFKA_BROKERS}
  delayBeforeKafkaInitialization: 5
  security:
    enabled: FALSE
  topics:
    processingTopic: privat-soknadinnsending-processingeventlog-v1-dev
    messageTopic: privat-soknadinnsending-messages-v1-dev
    arkiveringstilbakemeldingTopic: privat-soknadinnsending-arkiveringstilbakemeldinger-v1-dev
    metricsTopic: privat-soknadinnsending-metrics-v1-dev
    nologinSubmissionTopic: privat-soknadinnsending-nologin-submission-v1-dev
    loggedinSubmissionTopic: privat-soknadinnsending-loggedin-submission-v1-dev
    processingTopicV3: privat-soknadinnsending-processingeventlog-v3-dev
    metricsTopicV3: privat-soknadinnsending-metrics-v3-dev
services:
  tasklist:
    scheduling:
      startUpSeconds: 8
      secondsBetweenRetries: [0, 1, 1, 1, 1, 1]

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}
          audiences: ${AZURE_APP_CLIENT_ID}
      client:
        registration:
          arkiv:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            provider: azuread
            authorization-grant-type: client_credentials
            scope:  ${DOKARKIV_SCOPE}
          saf-maskintilmaskin:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            provider: azuread
            authorization-grant-type: client_credentials
            scope: ${SAF_SCOPE}
          innsendingApi:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            provider: azuread
            authorization-grant-type: client_credentials
            scope: ${INNSENDING_API_SCOPE}

        provider:
          azuread:
            token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}

auth:
  issuers:
    azuread:
      issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
      jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}


joark:
  host: ${JOARK_HOST}
  sendToJoark: true
  journal-post: /rest/journalpostapi/v1/journalpost
innsendingapi:
  host: ${INNSENDING_API_HOST}
saf:
  url: ${SAF_URL}
  path: /graphql
applicationName: "soknadsarkiverer"
status_log_url: "https://logs.adeo.no"

