server:
  port: 8091

cron:
  startRetryOfFailedArchiving: 0 00 12 22 JUN ?
failedApplications: ""

filefetchtimeouts:
  connectTimeout: 20
  callTimeout: 302
  readTimeout: 5
  writeTimeout: 5

archivingtimeouts:
  connectTimeout: 2
  readTimeout: 4
  exchangeTimeout: 4

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
kafka:
  applicationId: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  bootstrappingTimeout: 120
  delayBeforeKafkaInitialization: 5
  security:
    enabled: ${KAFKA_SECURITY}
    protocol: SSL
    keyStoreType: PKCS12
    keyStorePath: ${KAFKA_KEYSTORE_PATH}
    keyStorePassword: ${KAFKA_CREDSTORE_PASSWORD}
    trustStorePath: ${KAFKA_TRUSTSTORE_PATH}
    trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD}
  topics:
    processingTopic: ${KAFKA_PROCESSING_TOPIC}
    messageTopic: ${KAFKA_MESSAGE_TOPIC}
    arkiveringstilbakemeldingTopic: ${KAFKA_ARKIVERINGSTILBAKEMELDING_TOPIC}
    metricsTopic: ${KAFKA_METRICS_TOPIC}
    nologinSubmissionTopic: ${KAFKA_NOLOGIN_SUBMISSION_TOPIC}
    loggedinSubmissionTopic: ${KAFKA_LOGGEDIN_SUBMISSION_TOPIC}
    processingTopicV3: ${KAFKA_PROCESSING_TOPIC_V3:privat-soknadinnsending-processingeventlog-v3}
    metricsTopicV3: ${KAFKA_METRICS_TOPIC_V3:privat-soknadinnsending-metrics-v3}
  schemaRegistry:
    url: ${KAFKA_SCHEMA_REGISTRY}
    username: ${KAFKA_SCHEMA_REGISTRY_USER}
    password: ${KAFKA_SCHEMA_REGISTRY_PASSWORD}
services:
  tasklist:
    scheduling:
      startUpSeconds: 90
      secondsBetweenRetries: [1, 30, 60, 300, 1200, 3600, 21600]
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
joark:
  host: ${JOARK_HOST}
  sendToJoark: ${SEND_TO_JOARK}
  journal-post: /rest/journalpostapi/v1/journalpost
innsendingapi:
  host: ${INNSENDING_API_HOST}
saf:
  url: ${SAF_URL}
  path: /graphql
applicationName: "soknadsarkiverer"
status_log_url: ${STATUS_LOG_URL}

---
spring:
  config:
    activate:
      on-profile: dev

services:
  tasklist:
    scheduling:
      startUpSeconds: 90
      secondsBetweenRetries: [1, 5, 10, 15, 20, 25, 30]

---
spring:
  config:
    activate:
      on-profile: default | dev | prod

  security:
    oauth2:
      resourceserver:
        jwt:
          token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}
          audiences: ${AZURE_APP_CLIENT_ID}
      client:
        registration:
          arkiv:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            provider: azuread
            authorization-grant-type: client_credentials
            scope:  ${DOKARKIV_SCOPE}
          saf-maskintilmaskin:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            provider: azuread
            authorization-grant-type: client_credentials
            scope: ${SAF_SCOPE}
          innsendingApi:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            provider: azuread
            authorization-grant-type: client_credentials
            scope: ${INNSENDING_API_SCOPE}

        provider:
          azuread:
            token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}

failedApplications: ${FAILED_APPLICATIONS}
applicationName: ${NAIS_APP_NAME}

auth:
  issuers:
    azuread:
      token-uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
      jwk-set-uri: ${AZURE_OPENID_CONFIG_JWKS_URI}
      audiences: ${AZURE_APP_CLIENT_ID}

---
spring:
  config:
    activate:
      on-profile: prod

springdoc.api-docs.enabled: false
