name: Install and test
on:
  pull_request:
        paths-ignore:
          - '**.md'
          - '**/**.md'
          - '.github/workflows/**.yml'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Maven clean install
        run: mvn clean install


